# Generated by Django 4.1.3 on 2022-11-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menudb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='cuisine_id',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='price',
            field=models.FloatField(default=None),
        ),
    ]
