# Generated by Django 4.1.3 on 2022-11-09 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menudb', '0002_remove_menuitem_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='menudb.category'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='cuisine_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='menudb.cuisine'),
        ),
    ]
